// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

//namespace EVCS.TriNM.Repositories.Models;
namespace EVCS.SOAPAPIServices.TriNM.SOAPModels;

[DataContract]
public partial class ChargingTransaction
{
    [DataMember]
    public long TransactionId { get; set; }

    [DataMember]
    public int UserAccountId { get; set; }

    [DataMember]
    public int ChargerId { get; set; }

    [DataMember]
    public DateTime StartTime { get; set; }

    [DataMember]
    public DateTime? EndTime { get; set; }

    [DataMember]
    public decimal? EnergyConsumed { get; set; }

    [DataMember]
    public decimal Amount { get; set; }

    [DataMember]
    public string PaymentStatus { get; set; }

    [DataMember]
    public string PaymentMethod { get; set; }

    [DataMember]
    public DateTime? CreatedDate { get; set; }

    [DataMember]
    public virtual Charger Charger { get; set; }

    [DataMember]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [DataMember]
    public virtual UserAccount UserAccount { get; set; }
}