// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace EVCS.SOAPAPIServices.TriNM.SOAPModels;

[DataContract]
public partial class Charger
{
    [DataMember]
    public int ChargerId { get; set; }

    [DataMember]
    public int StationId { get; set; }

    [DataMember]
    public string ChargerType { get; set; }

    [DataMember]
    public bool IsAvailable { get; set; }

    [DataMember]
    public virtual ICollection<ChargingTransaction> ChargingTransactions { get; set; } = new List<ChargingTransaction>();

    [DataMember]
    public virtual Station Station { get; set; }
}