// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace EVCS.SOAPAPIServices.TriNM.SOAPModels;
 
[DataContract]
public partial class Payment
{
    [DataMember]
    public long PaymentId { get; set; }

    [DataMember]
    public long TransactionId { get; set; }

    [DataMember]
    public string PaymentMethod { get; set; }

    [DataMember]
    public decimal Amount { get; set; }

    [DataMember]
    public DateTime? PaidDate { get; set; }

    [DataMember]
    public string PaymentStatus { get; set; }

    [DataMember]
    public virtual ChargingTransaction Transaction { get; set; }
}