// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace EVCS.SOAPAPIServices.TriNM.SOAPModels;

[DataContract]
public partial class Station
{
    [Key]
    [DataMember]
    public int StationId { get; set; }

    [Required(ErrorMessage = "Station Code is required")]
    [MaxLength(50, ErrorMessage = "Station Code cannot exceed 50 characters")]
    [DataMember]
    public string StationCode { get; set; }

    [Required(ErrorMessage = "Station Name is required")]
    [MaxLength(100, ErrorMessage = "Station Name cannot exceed 100 characters")]
    [DataMember]
    public string StationName { get; set; }

    [Required(ErrorMessage = "Address is required")]
    [MaxLength(200, ErrorMessage = "Address cannot exceed 200 characters")]
    [DataMember]
    public string Address { get; set; }

    [MaxLength(100, ErrorMessage = "City cannot exceed 100 characters")]
    [DataMember]
    public string City { get; set; }

    [MaxLength(100, ErrorMessage = "Province cannot exceed 100 characters")]
    [DataMember]
    public string Province { get; set; }

    [Range(-90, 90, ErrorMessage = "Latitude must be between -90 and 90")]
    [DataMember]
    public decimal? Latitude { get; set; }

    [Range(-180, 180, ErrorMessage = "Longitude must be between -180 and 180")]
    [DataMember]
    public decimal? Longitude { get; set; }

    [Range(1, 1000, ErrorMessage = "Capacity must be between 1 and 1000")]
    [DataMember]
    public int Capacity { get; set; }

    [Range(0, 1000, ErrorMessage = "Current Available must be between 0 and 1000")]
    [DataMember]
    public int CurrentAvailable { get; set; }

    [Required(ErrorMessage = "Owner is required")]
    [MaxLength(150, ErrorMessage = "Owner cannot exceed 150 characters")]
    [DataMember]
    public string Owner { get; set; }

    [Phone(ErrorMessage = "Invalid phone number format")]
    [MaxLength(20, ErrorMessage = "Contact Phone cannot exceed 20 characters")]
    [DataMember]
    public string ContactPhone { get; set; }

    [EmailAddress(ErrorMessage = "Invalid email format")]
    [MaxLength(150, ErrorMessage = "Contact Email cannot exceed 150 characters")]
    [DataMember]
    public string ContactEmail { get; set; }

    [MaxLength(500, ErrorMessage = "Description cannot exceed 500 characters")]
    [DataMember]
    public string Description { get; set; }

    [DataMember]
    public DateTime CreatedDate { get; set; }

    [DataMember]
    public DateTime? ModifiedDate { get; set; }

    [DataMember]
    public bool IsActive { get; set; }

    [DataMember]
    public virtual ICollection<Charger> Chargers { get; set; } = new List<Charger>();
}