// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace EVCS.SOAPAPIServices.TriNM.SOAPModels;

[DataContract]
public partial class UserAccount
{
    [DataMember]
    public int UserAccountId { get; set; }

    [DataMember]
    public string UserName { get; set; }

    [DataMember]
    public string PasswordHash { get; set; }

    [DataMember]
    public string FullName { get; set; }

    [DataMember]
    public string Email { get; set; }

    [DataMember]
    public string Phone { get; set; }

    [DataMember]
    public string EmployeeCode { get; set; }

    [DataMember]
    public int RoleId { get; set; }

    [DataMember]
    public DateTime? CreatedDate { get; set; }

    [DataMember]
    public DateTime? ModifiedDate { get; set; }

    [DataMember]
    public bool IsActive { get; set; }

    [DataMember]
    public string GoogleId { get; set; }

    [DataMember]
    public string PhotoUrl { get; set; }

    [DataMember]
    public virtual ICollection<ChargingTransaction> ChargingTransactions { get; set; } = new List<ChargingTransaction>();
}