// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EVCS.TriNM.Repositories.Models;

public partial class EVChargingDBContext : DbContext
{
    public EVChargingDBContext()
    {
    }

    public EVChargingDBContext(DbContextOptions<EVChargingDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChargerTriNM> ChargerTriNMs { get; set; }

    public virtual DbSet<ChargingTransaction> ChargingTransactions { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<StationTriNM> StationTriNMs { get; set; }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-UPKPODR8;Initial Catalog=EVChargingDB;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChargerTriNM>(entity =>
        {
            entity.ToTable("ChargerTriNM");

            entity.Property(e => e.ChargerTriNMId).HasColumnName("ChargerTriNMID");
            entity.Property(e => e.ChargerTriNMType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);
            
            entity.Property(e => e.StationTriNMId).HasColumnName("StationTriNMID");
            entity.Property(e => e.ImageURL).HasMaxLength(500);


            entity.HasOne(d => d.StationTriNM).WithMany(p => p.ChargerTriNMs)
                .HasForeignKey(d => d.StationTriNMId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChargerTriNM_StationTriNM");
        });

        modelBuilder.Entity<ChargingTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId);

            entity.ToTable("ChargingTransaction");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.Amount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.ChargerTriNMId).HasColumnName("ChargerTriNMID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.EnergyConsumed).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");

            entity.HasOne(d => d.ChargerTriNM).WithMany(p => p.ChargingTransactions)
                .HasForeignKey(d => d.ChargerTriNMId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transaction_ChargerTriNM");

            entity.HasOne(d => d.UserAccount).WithMany(p => p.ChargingTransactions)
                .HasForeignKey(d => d.UserAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transaction_User");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.PaidDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");

            entity.HasOne(d => d.Transaction).WithMany(p => p.Payments)
                .HasForeignKey(d => d.TransactionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payment_Transaction");
        });

        modelBuilder.Entity<StationTriNM>(entity =>
        {
            entity.ToTable("StationTriNM");

    
            entity.Property(e => e.StationTriNMId).HasColumnName("StationTriNMID");
            entity.Property(e => e.StationTriNMCode).HasMaxLength(50);
            entity.Property(e => e.StationTriNMName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.Province).HasMaxLength(100);
            entity.Property(e => e.Latitude).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Capacity).HasColumnType("int");
            entity.Property(e => e.CurrentAvailable).HasColumnType("int");
            entity.Property(e => e.Owner).HasMaxLength(150);
            entity.Property(e => e.ContactPhone).HasMaxLength(20);
            entity.Property(e => e.ContactEmail).HasMaxLength(150);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ImageURL).HasMaxLength(500);
        });

        modelBuilder.Entity<UserAccount>(entity =>
        {
            entity.ToTable("UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode).HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.GoogleId).HasMaxLength(256);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.PhotoUrl).HasMaxLength(500);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}