//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVCS.WCFRefference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/EVCS.SOAPAPIServices.TriNM.SOAPModels")]
    public partial class Station : object
    {
        
        private string AddressField;
        
        private int CapacityField;
        
        private EVCS.WCFRefference.Charger[] ChargersField;
        
        private string CityField;
        
        private string ContactEmailField;
        
        private string ContactPhoneField;
        
        private System.DateTime CreatedDateField;
        
        private int CurrentAvailableField;
        
        private string DescriptionField;
        
        private bool IsActiveField;
        
        private System.Nullable<decimal> LatitudeField;
        
        private System.Nullable<decimal> LongitudeField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private string OwnerField;
        
        private string ProvinceField;
        
        private string StationCodeField;
        
        private int StationIdField;
        
        private string StationNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity
        {
            get
            {
                return this.CapacityField;
            }
            set
            {
                this.CapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.Charger[] Chargers
        {
            get
            {
                return this.ChargersField;
            }
            set
            {
                this.ChargersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail
        {
            get
            {
                return this.ContactEmailField;
            }
            set
            {
                this.ContactEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone
        {
            get
            {
                return this.ContactPhoneField;
            }
            set
            {
                this.ContactPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentAvailable
        {
            get
            {
                return this.CurrentAvailableField;
            }
            set
            {
                this.CurrentAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner
        {
            get
            {
                return this.OwnerField;
            }
            set
            {
                this.OwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationCode
        {
            get
            {
                return this.StationCodeField;
            }
            set
            {
                this.StationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StationId
        {
            get
            {
                return this.StationIdField;
            }
            set
            {
                this.StationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationName
        {
            get
            {
                return this.StationNameField;
            }
            set
            {
                this.StationNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Charger", Namespace="http://schemas.datacontract.org/2004/07/EVCS.SOAPAPIServices.TriNM.SOAPModels")]
    public partial class Charger : object
    {
        
        private int ChargerIdField;
        
        private string ChargerTypeField;
        
        private EVCS.WCFRefference.ChargingTransaction[] ChargingTransactionsField;
        
        private bool IsAvailableField;
        
        private EVCS.WCFRefference.Station StationField;
        
        private int StationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargerId
        {
            get
            {
                return this.ChargerIdField;
            }
            set
            {
                this.ChargerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargerType
        {
            get
            {
                return this.ChargerTypeField;
            }
            set
            {
                this.ChargerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.ChargingTransaction[] ChargingTransactions
        {
            get
            {
                return this.ChargingTransactionsField;
            }
            set
            {
                this.ChargingTransactionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.Station Station
        {
            get
            {
                return this.StationField;
            }
            set
            {
                this.StationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StationId
        {
            get
            {
                return this.StationIdField;
            }
            set
            {
                this.StationIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargingTransaction", Namespace="http://schemas.datacontract.org/2004/07/EVCS.SOAPAPIServices.TriNM.SOAPModels")]
    public partial class ChargingTransaction : object
    {
        
        private decimal AmountField;
        
        private EVCS.WCFRefference.Charger ChargerField;
        
        private int ChargerIdField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private System.Nullable<System.DateTime> EndTimeField;
        
        private System.Nullable<decimal> EnergyConsumedField;
        
        private string PaymentMethodField;
        
        private string PaymentStatusField;
        
        private EVCS.WCFRefference.Payment[] PaymentsField;
        
        private System.DateTime StartTimeField;
        
        private long TransactionIdField;
        
        private EVCS.WCFRefference.UserAccount UserAccountField;
        
        private int UserAccountIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.Charger Charger
        {
            get
            {
                return this.ChargerField;
            }
            set
            {
                this.ChargerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargerId
        {
            get
            {
                return this.ChargerIdField;
            }
            set
            {
                this.ChargerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EnergyConsumed
        {
            get
            {
                return this.EnergyConsumedField;
            }
            set
            {
                this.EnergyConsumedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.UserAccount UserAccount
        {
            get
            {
                return this.UserAccountField;
            }
            set
            {
                this.UserAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserAccountId
        {
            get
            {
                return this.UserAccountIdField;
            }
            set
            {
                this.UserAccountIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/EVCS.SOAPAPIServices.TriNM.SOAPModels")]
    public partial class UserAccount : object
    {
        
        private EVCS.WCFRefference.ChargingTransaction[] ChargingTransactionsField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string EmailField;
        
        private string EmployeeCodeField;
        
        private string FullNameField;
        
        private bool IsActiveField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private string PasswordHashField;
        
        private string PhoneField;
        
        private int RoleIdField;
        
        private int UserAccountIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.ChargingTransaction[] ChargingTransactions
        {
            get
            {
                return this.ChargingTransactionsField;
            }
            set
            {
                this.ChargingTransactionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCode
        {
            get
            {
                return this.EmployeeCodeField;
            }
            set
            {
                this.EmployeeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash
        {
            get
            {
                return this.PasswordHashField;
            }
            set
            {
                this.PasswordHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserAccountId
        {
            get
            {
                return this.UserAccountIdField;
            }
            set
            {
                this.UserAccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/EVCS.SOAPAPIServices.TriNM.SOAPModels")]
    public partial class Payment : object
    {
        
        private decimal AmountField;
        
        private System.Nullable<System.DateTime> PaidDateField;
        
        private long PaymentIdField;
        
        private string PaymentMethodField;
        
        private string PaymentStatusField;
        
        private EVCS.WCFRefference.ChargingTransaction TransactionField;
        
        private long TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaidDate
        {
            get
            {
                return this.PaidDateField;
            }
            set
            {
                this.PaidDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PaymentId
        {
            get
            {
                return this.PaymentIdField;
            }
            set
            {
                this.PaymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EVCS.WCFRefference.ChargingTransaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EVCS.WCFRefference.IStationSOAPServices")]
    public interface IStationSOAPServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/GetAll", ReplyAction="http://tempuri.org/IStationSOAPServices/GetAllResponse")]
        System.Threading.Tasks.Task<EVCS.WCFRefference.Station[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/Get", ReplyAction="http://tempuri.org/IStationSOAPServices/GetResponse")]
        System.Threading.Tasks.Task<EVCS.WCFRefference.Station> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/SearchStations", ReplyAction="http://tempuri.org/IStationSOAPServices/SearchStationsResponse")]
        System.Threading.Tasks.Task<EVCS.WCFRefference.Station[]> SearchStationsAsync(string searchTerm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/GetAvailableStations", ReplyAction="http://tempuri.org/IStationSOAPServices/GetAvailableStationsResponse")]
        System.Threading.Tasks.Task<EVCS.WCFRefference.Station[]> GetAvailableStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/CreateStation", ReplyAction="http://tempuri.org/IStationSOAPServices/CreateStationResponse")]
        System.Threading.Tasks.Task<int> CreateStationAsync(EVCS.WCFRefference.Station station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/UpdateStation", ReplyAction="http://tempuri.org/IStationSOAPServices/UpdateStationResponse")]
        System.Threading.Tasks.Task<int> UpdateStationAsync(EVCS.WCFRefference.Station station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/DeleteStation", ReplyAction="http://tempuri.org/IStationSOAPServices/DeleteStationResponse")]
        System.Threading.Tasks.Task<int> DeleteStationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/ActivateStation", ReplyAction="http://tempuri.org/IStationSOAPServices/ActivateStationResponse")]
        System.Threading.Tasks.Task<bool> ActivateStationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSOAPServices/UpdateAvailability", ReplyAction="http://tempuri.org/IStationSOAPServices/UpdateAvailabilityResponse")]
        System.Threading.Tasks.Task<bool> UpdateAvailabilityAsync(int stationId, int newAvailable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IStationSOAPServicesChannel : EVCS.WCFRefference.IStationSOAPServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class StationSOAPServicesClient : System.ServiceModel.ClientBase<EVCS.WCFRefference.IStationSOAPServices>, EVCS.WCFRefference.IStationSOAPServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StationSOAPServicesClient() : 
                base(StationSOAPServicesClient.GetDefaultBinding(), StationSOAPServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStationSOAPServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StationSOAPServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(StationSOAPServicesClient.GetBindingForEndpoint(endpointConfiguration), StationSOAPServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StationSOAPServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StationSOAPServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StationSOAPServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StationSOAPServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StationSOAPServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EVCS.WCFRefference.Station[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<EVCS.WCFRefference.Station> GetAsync(int id)
        {
            return base.Channel.GetAsync(id);
        }
        
        public System.Threading.Tasks.Task<EVCS.WCFRefference.Station[]> SearchStationsAsync(string searchTerm)
        {
            return base.Channel.SearchStationsAsync(searchTerm);
        }
        
        public System.Threading.Tasks.Task<EVCS.WCFRefference.Station[]> GetAvailableStationsAsync()
        {
            return base.Channel.GetAvailableStationsAsync();
        }
        
        public System.Threading.Tasks.Task<int> CreateStationAsync(EVCS.WCFRefference.Station station)
        {
            return base.Channel.CreateStationAsync(station);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStationAsync(EVCS.WCFRefference.Station station)
        {
            return base.Channel.UpdateStationAsync(station);
        }
        
        public System.Threading.Tasks.Task<int> DeleteStationAsync(int id)
        {
            return base.Channel.DeleteStationAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> ActivateStationAsync(int id)
        {
            return base.Channel.ActivateStationAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAvailabilityAsync(int stationId, int newAvailable)
        {
            return base.Channel.UpdateAvailabilityAsync(stationId, newAvailable);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStationSOAPServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.None; // Changed to None for HTTP
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStationSOAPServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5046/StationService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StationSOAPServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStationSOAPServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StationSOAPServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStationSOAPServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStationSOAPServices,
        }
    }
}
